name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install php8.2-cli php8.2-common php8.2-xml php8.2-mbstring php8.2-sqlite3 php8.2-mysql php8.2-pgsql php8.2-gd php8.2-xdebug -y
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: log/coverage-cobertura.xml

    - name: Run PHPCS (PHP Code Sniffer)
      run: ./vendor/bin/phpcs --standard=PSR12 ./lib

    - name: Run PHPMD (PHP Mess Detector)
      run: ./vendor/bin/phpmd ./lib text cleancode

    - name: Run PHPStan (PHP Static Analysis)
      run: ./vendor/bin/phpstan analyse --level=5 ./lib
